#!/usr/bin/env bash
# Installs and configures nginx to return Holberton School at root
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
```

