#!/usr/bin/env bash
# Configures Nginx with a 301 redirect on /redirect_me
apt-get update -y
apt-get install -y nginx

rm -f /var/www/html/index.html
rm -f /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.html
chmod 644 /var/www/html/index.html

printf "server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\n\troot /var/www/html;\n\tindex index.html index.htm;\n\n\tserver_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}\n" > /etc/nginx/sites-available/default

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

nginx -t && service nginx restart
